# Generated by Django 5.0.7 on 2024-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0002_alter_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesperson",
            name="picture_url",
            field=models.URLField(
                blank=True,
                default="https://t4.ftcdn.net/jpg/02/15/84/43/360_F_215844325_ttX9YiIIyeaR7Ne6EaLLjMAmy4GvPC69.jpg",
                null=True,
            ),
        ),
    ]
