# Generated by Django 5.0.7 on 2024-07-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automobilevo",
            name="import_href",
            field=models.CharField(default="null", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
