# Generated by Django 5.0.7 on 2024-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0002_automobilevo_import_href"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="date_time",
        ),
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="time",
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
