# Generated by Django 5.0.7 on 2024-07-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_rest", "0002_automobile_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
